### ISSUE TITLE
Integration with a Symfony 2.0.17 project

### ISSUE THREAD

**Issue by beraneck** [beraneck/php-ews#1]
Asked by clafouti2104  :

Hello,
I downloaded the PSR-0 compliant version but how can i integrate in my Symfony 2.0.17 project?
Here's an extract of my autoload.php :

$loader->registerNamespaces(array(
'PhpEws' => DIR.'/../vendor/PhpEws',
));

My vendor/PhpEws directory :
- EWSType directory
- NTLMSoapClient directory
- wsdl directory
- EWSAutodiscover.php
- EWSException.php
- ExchangeWebServices.php
- NTMLSoapClient.php

Then I got the error 'class ExchangeWebServices not found' when I run this kind of example :

use ExchangeWebServices;
use EWS_Exception;

class XXX {
public function test() {
$ews = new ExchangeWebServices($host, $user, $password, $version);

}
}

Do you have an idea?
Thanks a lot

**Comment by beraneck** [comment]
Hello !

First keep the directory structure of the project and store it in /vendor/php-ews/ or something like that.
( It should contains composer.json, CONTRIBUTORS.txt, LICENSE.txt, PhpEws, README.md)

Then in the autoload : 

``` php
$loader->registerNamespaces(array(
...
    'PhpEws'           => __DIR__.'/../vendor/php-ews'
...
));
```

Then make the use like this : 

``` php
use PhpEws\ExchangeWebServices;
```

Keep in mind that the class names have changed to match the filename.
All the types have lost their EWSType_ prefix. They use now a specific namespace :

``` php
use PhpEws\EwsType\...
```

Hop it helps !

**Comment by clafouti2104** [comment]
Thanks for the answer, you resolve my problem! Now I don't have the 'class not found' error anymore.
However, I got the error "Runtime Notice: Creating default object from empty value" when I execute this code :

$ews = new ExchangeWebServices($this->host, $this->user, $this->password, $this->version);
$request = new FindItemType();
$request->Traversal = FolderQueryTraversalType::SHALLOW;
$startDateEvent = '2013-01-09T00:00:00'; //ie: 2010-09-14T09:00:00
$endDateEvent = '2013-01-09T10:00:00'; //ie: 2010-09-20T17:00:00
$request->CalendarView->StartDate = $startDateEvent; 

Do you have an idea?
Thanks

**Comment by beraneck** [comment]
Hello !

I think the problem is here : 

$request->CalendarView->StartDate = $startDateEvent;

you should do something like : 

$request->CalendarView = new CalendarViewType();

and then

$request->CalendarView->StartDate = '2013-01-09T00:00:00';

BR

**Comment by majuansari** [comment]
How will i used this with latest Symfony version ? [2.3]

I am using the following way in app/autoload.php  
$loader->add('PhpEws' , **DIR**.'/../vendor/php-ews');

as $loader->registerNamespaces is not working

Can u help me in how to use with latest version ?

**Comment by beraneck** [comment]
Hi !

I never tried with v 2.3 but since symfony 2.1 you can use (have to use) composer. You have to modify your composer.json : 

add a repository section (as the project is not published on packagist.org) : 

``` javascript
"repositories": [
    {
            "type": "vcs",
            "url": "https://github.com/beraneck/php-ews.git"
        }
    ],
```

And add in the "require" section : 

``` javascript
"require": {
        ...
        "jamesiarmes/php-ews":"*",
        ....
   }
```

Then do a 

``` bash
composer update 
```

and the package is automatically downloaded and added to autoload.

BR

**Comment by majuansari** [comment]
thanks bro

**Comment by plopplap** [comment]
Hi,

I try to add your package but I have this message :
 Problem 1
    - The requested package jamesiarmes/php-ews could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for symfony/framework-standard-edition 2.4.x-dev -> satisfiable by symfony/framework-standard-edition[2.4.x-dev].
    - symfony/framework-standard-edition 2.4.x-dev requires jamesiarmes/php-ews \* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Can you help me please?

**Comment by plopplap** [comment]
It's ok, i just have to add this line in my composer.json : "minimum-stability": "dev",
